---
name: '[bot] Synchronize labels'
on:
  push:
    branches: [master]
    paths: [.github/workflows/github.labeler.yaml, .github/labels.yaml]
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    name: Synchronize labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
          prune: true
