---
name: '[bot] Update documentation assets (master only)'
on:
  push:
    branches: [master]

jobs:
  generate-docs-assets:
    name: Update documentation assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: heinrichreimer/github-changelog-generator-action@e60b5a2bd9fcd88dadf6345ff8327863fb8b490f # v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # NOTE: seems impossible to use terraform-docs/gh-actions with EndBug/add-and-commit... so
      #       we will do everything manually
      - name: Generate README.md with terraform-docs
        run: |
          mkdir --parent .terraform-docs
          curl -L "https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz" | tar -xvzC .terraform-docs
          chmod +x .terraform-docs/terraform-docs
          
          .terraform-docs/terraform-docs .
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          default_author: github_actions
          message: "Update documentation assets"
