name: Security hardening (Terraform)

on:
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0 # 0.14.0
        with:
          scan-type: config
          scan-ref: .
          exit-code: 1
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
